export const translations = {
  PT: {
    streakTitle: 'RITMO DE PERFORMANCE',
    greeting: 'Oi,',
    level: 'INGLÊS FLUIDEZ B1',
    levelA1: 'Desbravador A1',
    levelA2: 'Viajante A2',
    levelB1: 'INGLÊS FLUIDEZ B1',
    levelB2: 'Estrategista B2',
    levelC1: 'Fluente C1',
    levelC2: 'Mestre C2',
    welcome: "Olá", 
    journey: "RUMO AO NÍVEL", 
    missionTag: "ESTRUTURA DO MÓDULO", 
    module: "MÓDULO 01",
    trainBtn: "AVANÇAR", 
    trainBtnRaw: "AVANÇAR",
    streak: "RACHA DE RETENÇÃO", 
    streakSub: 'MANTENHA A CONSTÂNCIA HOJE',
    ranking: "PROGRESSO DA UNIDADE", 
    nextReward: "PRÓXIMO CICLO",
    radarTitle: "ANÁLISE DE COMPETÊNCIAS", 
    leaderboard: "RANKING GLOBAL: TOP 10 PERFORMANCE",
    evalBtn: "AVALIAR", 
    submitBtn: "ENTREGA",
    calBtn: "AGENDA",
    chestTitle: "LOG DE ERROS FREQUENTES", 
    clearBtn: "DEPURAR LOG",
    insights: ["Escuta +15%", "Escrita +20%", "Prática de Fala"],
    reward: 'SCORE ATIVO: +50 PTS', 
    time: "TEMPO: 15 MIN", 
    badge: "Nível: Explorador",
    mastery: 'MÉTRICA DE ABSORÇÃO: 65%', 
    toNext: '35% PARA NOVA INSÍGNIA',
    classAccess: "ACESSO À AULA",
    classEnter: "🚀 ENTRAR NA AULA AGORA",
    classLate: "⚠️ SUA AULA JÁ COMEÇOU!",
    botSpeech: "⚡ Você está indo muito bem! Complete a missão para garantir seus pontos de hoje!"
  },
  EN: {
    streakTitle: 'PERFORMANCE RHYTHM',
    greeting: 'Hi,',
    level: 'ENGLISH B1 FLUENCY',
    levelA1: 'Explorer A1',
    levelA2: 'Voyager A2',
    levelB1: 'ENGLISH B1 FLUENCY',
    levelB2: 'Strategist B2',
    levelC1: 'Fluent C1',
    levelC2: 'Master C2',
    welcome: "Hi", 
    journey: "TARGET LEVEL", 
    missionTag: "MODULE STRUCTURE", 
    module: "MODULE 01",
    trainBtn: "ADVANCE", 
    trainBtnRaw: "ADVANCE",
    streak: "RETENTION STREAK", 
    streakSub: 'MAINTAIN CONSISTENCY TODAY',
    ranking: "UNIT PROGRESS", 
    nextReward: "NEXT REWARD BATCH",
    radarTitle: "COMPETENCY ANALYSIS", 
    leaderboard: "GLOBAL RANKING: TOP 10 PERFORMANCE",
    evalBtn: "EVALUATE", 
    submitBtn: "TASK",
    calBtn: "CALENDAR",
    chestTitle: "RECURRING ERRORS LOG", 
    clearBtn: "DEBUG LOG",
    insights: ["Listen +15%", "Write +20%", "Speaking Practice"],
    reward: 'ACTIVE SCORE: +50 PTS', 
    time: "TIME: 15 MIN", 
    badge: "Nível: Explorador",
    mastery: 'ABSORPTION METRIC: 65%', 
    toNext: '35% TO NEXT BADGE',
    classAccess: "CLASS ACCESS",
    classEnter: "🚀 ENTER CLASS NOW",
    classLate: "⚠️ YOUR CLASS HAS ALREADY STARTED!",
    botSpeech: "⚡ You're doing amazing! Complete the mission to lock in your points today!"
  },
  ES: {
    streakTitle: 'RITMO DE RENDIMIENTO',
    greeting: 'Hola,',
    level: 'INGLÉS FLUIDEZ B1',
    levelA1: 'Explorador A1',
    levelA2: 'Viajero A2',
    levelB1: 'INGLÉS FLUIDEZ B1',
    levelB2: 'Estratega B2',
    levelC1: 'Fluente C1',
    levelC2: 'Maestro C2',
    welcome: "Hola", 
    journey: "RUMBO AL NIVEL", 
    missionTag: "ESTRUCTURA DEL MÓDULO", 
    module: "MÓDULO 01",
    trainBtn: "AVANZAR", 
    trainBtnRaw: "AVANZAR",
    streak: "RACHA DE RETENCIÓN", 
    streakSub: 'MANTENGA LA CONSTANCIA HOY',
    ranking: "AVANCES DE LA UNIDAD", 
    nextReward: "PRÓXIMO CICLO",
    radarTitle: "ANÁLISIS DE COMPETENCIAS", 
    leaderboard: "RANKING GLOBAL: TOP 10 PERFORMANCE",
    evalBtn: "EVALUAR", 
    submitBtn: "ENTREGA",
    calBtn: "AGENDA",
    chestTitle: "LOG DE ERRORES FRECUENTES", 
    clearBtn: "DEPURAR LOG",
    insights: ["Escucha +15%", "Escritura +20%", "Prática de Habla"],
    reward: 'SCORE ATIVO: +50 PTS', 
    time: "TIEMPO: 15 MIN", 
    badge: "Nivel: Explorador",
    mastery: 'MÉTRICA DE ABSORCIÓN: 65%', 
    toNext: '35% PARA SIGUIENTE INSIGNIA',
    classAccess: "ACCESO A LA CLASE",
    classEnter: "🚀 ENTRAR A LA CLASE AHORA",
    classLate: "⚠️ ¡TU CLASE YA HA COMENZADO!",
    botSpeech: "⚡ ¡Lo estás haciendo genial! ¡Completa la missão para asegurar tus puntos de hoy!"
  }
};
